### ISSUE TITLE
Remove space separator

### ISSUE THREAD

**Issue by mkr4** [saiga006/message-finder#2]
Hello!
Could you replace space separator with something else? I want to use multiple word phase as alert trigger, but 'hello there' had been parsed as two alerts [ 'hello', 'there' ].

**Comment by saiga006** [comment]
Hi @mkr4 ,

You could fork the project and modify the keyword separation logic at the below places for your usecase, 
https://github.com/saiga006/message-finder/blob/master/app/src/main/java/com/saiga/find/messagefinder/MainActivity.java#L499 (UI keyword split logic)

https://github.com/saiga006/message-finder/blob/master/app/src/main/java/com/saiga/find/messagefinder/SMSReceiver.java#L82 (Received SMS comparison logic)

Thanks
